Added Homework 19
gbukhtatyi/it-academy-java pull request #14
Opened 2024-11-30 17:33 UTC by gbukhtatyi

2024-12-03 10:06 UTC, PavelIvanouski requested changes

2024-12-03 10:06 UTC, PavelIvanouski commented on src/homework19/library/BookManager.java
> +    public static List<Book> filterByAuthor(List<Book> books, String author) {
в параметрах дожлен быть Predicate, а не String, чтобы через лямбда выражение написать любое условие для фитрации

2024-12-03 10:06 UTC, PavelIvanouski commented on src/homework19/library/BookManager.java
> +    public static List<Book> filterByAmountPages(List<Book> books, int minAmountPages) {
в параметрах дожлен быть Comparator, а не int, чтобы через лямбда выражение написать любое условие для сортировки

2024-12-03 15:42 UTC, gbukhtatyi commented on src/homework19/library/BookManager.java
> +    public static List<Book> filterByAmountPages(List<Book> books, int minAmountPages) {
Поправил, добавлен новый метод sortedBy

2024-12-03 15:42 UTC, gbukhtatyi commented on src/homework19/library/BookManager.java
> +    public static List<Book> filterByAuthor(List<Book> books, String author) {
Поправил, добавлен новый метод filterBy

2024-12-05 10:58 UTC, PavelIvanouski approved these changes

2024-12-06 07:06 UTC, merged