Added Homework 2
gbukhtatyi/it-academy-java pull request #2
Opened 2024-09-16 05:59 UTC by gbukhtatyi

2024-09-16 09:25 UTC, PavelIvanouski requested changes

2024-09-16 09:25 UTC, PavelIvanouski commented on src/homework2/Homework2.java
> +        for (int i = 0; i < numbers.length; i++) {
тут можно без for обойтись

2024-09-16 10:30 UTC, gbukhtatyi commented on src/homework2/Homework2.java
> +        for (int i = 0; i < numbers.length; i++) {
Поправил

2024-09-17 08:01 UTC, PavelIvanouski requested changes

2024-09-17 08:01 UTC, PavelIvanouski commented on src/homework2/Homework2.java
> +        int result = (a + b + c + d + e) / 5;
а если результат будет дробным числом?

2024-09-17 15:23 UTC, gbukhtatyi commented on src/homework2/Homework2.java
> +        int result = (a + b + c + d + e) / 5;
Поправлено, int сменен на double

2024-09-19 12:23 UTC, merged

2024-09-20 08:13 UTC, PavelIvanouski reviewed
все ок