Added Homework 6
gbukhtatyi/it-academy-java pull request #5
Opened 2024-09-28 14:59 UTC by gbukhtatyi

2024-09-30 08:54 UTC, PavelIvanouski requested changes

2024-09-30 08:54 UTC, PavelIvanouski commented on src/Homework6/Homework6.java
> +        if (indexOf(arr, x)) {
зачем второй раз вызывать (indexOf(arr, x) если в строке 141 есть переменная result, которая уже хранит значение вызова?

2024-09-30 08:54 UTC, PavelIvanouski commented on src/Homework6/Homework6.java
> +    public static int[] fillArray(int[] arr) {
может метод назвать fillMirrorArray. а то если вдруг другой разработчик захочет его использовать. то может подумать, что это метод просто заполняет массив

2024-09-30 08:54 UTC, PavelIvanouski commented on src/Util/Input.java
> +package Util;
названия пакета обычно с маленькой буквы

2024-10-01 16:30 UTC, gbukhtatyi commented on src/Homework6/Homework6.java
> +    public static int[] fillArray(int[] arr) {
Поправил

2024-10-01 16:30 UTC, gbukhtatyi commented on src/Homework6/Homework6.java
> +        if (indexOf(arr, x)) {
Поправил

2024-10-01 16:30 UTC, gbukhtatyi commented on src/Util/Input.java
> +package Util;
Поправил

2024-10-02 07:15 UTC, PavelIvanouski approved these changes

2024-10-04 05:48 UTC, merged