Added Homework 7
gbukhtatyi/it-academy-java pull request #6
Opened 2024-10-05 19:10 UTC by gbukhtatyi

2024-10-07 07:05 UTC, PavelIvanouski requested changes

2024-10-07 07:05 UTC, PavelIvanouski commented on src/Homework7/TimePeriod.java
> +    protected int currentSeconds = 0;
"промежуток в классе должен задаваться тремя свойствами: секундами, минутами, часами" - три поля должно быть в классе

2024-10-07 07:05 UTC, PavelIvanouski commented on src/Homework7/TimePeriod.java
> +    public TimePeriod(int seconds) {
на основании секунд вычислять и заполнять все поля

2024-10-07 07:05 UTC, PavelIvanouski commented on src/Homework7/TimePeriod.java
> +        return currentSeconds;
все секунды на основании всех полей

2024-10-07 15:23 UTC, gbukhtatyi commented on src/Homework7/TimePeriod.java
> +    protected int currentSeconds = 0;
Поправил

2024-10-07 15:24 UTC, gbukhtatyi commented on src/Homework7/TimePeriod.java
> +    public TimePeriod(int seconds) {
Поправил

2024-10-07 15:24 UTC, gbukhtatyi commented on src/Homework7/TimePeriod.java
> +        return currentSeconds;
Поправил

2024-10-08 07:38 UTC, PavelIvanouski approved these changes

2024-10-08 07:47 UTC, merged