Added Homework 11
gbukhtatyi/it-academy-java pull request #8
Opened 2024-10-21 14:59 UTC by gbukhtatyi

2024-10-22 07:43 UTC, PavelIvanouski requested changes

2024-10-22 07:43 UTC, PavelIvanouski commented on src/Homework11/Money.java
> +    public boolean compareTo(Money obj) {
обычно compare возвращает int (0 если равны, > 1  или < 1)
а equals уже возвраащет boolean
лучше вместо isGreater использовать compare например

2024-10-22 07:43 UTC, PavelIvanouski commented on src/Homework11/airline/Company.java
> +    public FlyingMachine search(String name, int capacity, int loadCapacity) throws Exception {
для поиска отдельные методы, например поиск по вместимости принмиает диапазон от и до.
а если несколько подходят под поиск?

2024-10-23 07:38 UTC, gbukhtatyi commented on src/Homework11/Money.java
> +    public boolean compareTo(Money obj) {
Поправил

2024-10-23 07:38 UTC, gbukhtatyi commented on src/Homework11/airline/Company.java
> +    public FlyingMachine search(String name, int capacity, int loadCapacity) throws Exception {
Переделал функцию чтобы возвращала тип ArrayList<FlyingMachine>

2024-10-24 11:11 UTC, PavelIvanouski approved these changes

2024-10-25 16:43 UTC, merged